// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyECommerceWebApp.Infrastructure.Persistence;

#nullable disable

namespace MyECommerceWebApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816013451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Clientes_Email");

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_Apellido", "LEN(LTRIM(RTRIM([Apellido]))) > 0");

                            t.HasCheckConstraint("CK_Clientes_Email", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_Clientes_Nombre", "LEN(LTRIM(RTRIM([Nombre]))) > 0");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.LogEvento", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("MensajeLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistroId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("api");

                    b.HasKey("LogId");

                    b.HasIndex("FechaEvento")
                        .HasDatabaseName("IX_Logs_FechaEvento");

                    b.ToTable("Logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Logs_Operacion", "[Operacion] IN ('INSERT', 'UPDATE', 'DELETE', 'ERROR', 'PAGO', 'INVENTARIO')");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrdenId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Ordenes_Estado");

                    b.HasIndex("ClienteId", "FechaOrden")
                        .HasDatabaseName("IX_Ordenes_ClienteId");

                    b.ToTable("Ordenes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ordenes_Estado", "[Estado] IN ('pendiente', 'confirmada', 'cancelada', 'rechazada')");

                            t.HasCheckConstraint("CK_Ordenes_Total", "[Total] >= 0");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.OrdenDetalle", b =>
                {
                    b.Property<int>("OrdenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Cantidad] * [PrecioUnitario]", true);

                    b.HasKey("OrdenDetalleId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("OrdenId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrdenDetalle_Orden_Producto");

                    b.ToTable("OrdenDetalle", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrdenDetalle_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_OrdenDetalle_PrecioUnitario", "[PrecioUnitario] > 0");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MensajeError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PagoId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pagos_Estado");

                    b.HasIndex("OrdenId");

                    b.ToTable("Pagos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_Estado", "[Estado] IN ('autorizado', 'rechazado', 'pendiente')");

                            t.HasCheckConstraint("CK_Pagos_Intentos", "[Intentos] >= 0");

                            t.HasCheckConstraint("CK_Pagos_Monto", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Productos_Precio", "[Precio] > 0");

                            t.HasCheckConstraint("CK_Productos_Stock", "[Stock] >= 0");
                        });
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Orden", b =>
                {
                    b.HasOne("MyECommerceWebApp.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.OrdenDetalle", b =>
                {
                    b.HasOne("MyECommerceWebApp.Domain.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyECommerceWebApp.Domain.Entities.Producto", "Producto")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Pago", b =>
                {
                    b.HasOne("MyECommerceWebApp.Domain.Entities.Orden", "Orden")
                        .WithMany("Pagos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MyECommerceWebApp.Domain.Entities.Producto", b =>
                {
                    b.Navigation("OrdenDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
